<a href="https://colab.research.google.com/github/Nath188/Redes-Neuronales/blob/main/Dimensiones%2C_tensores_y_reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **DIMENSIONES, TENSORES Y RESHAPE**

In [12]:
import numpy as np

### Scalar

In [16]:
x = np.array(42)
print(x.shape)
x.ndim

()


0

## Vector

In [19]:
x = np.array([42,123,21,32,1,3,7])
print(x.shape)
x.ndim

(7,)


1

## Matrix

In [22]:
x = np.array([[42,23,123],
             [34,343,24]])
print(x.shape)
x.ndim

(2, 3)


2

## Tensor

In [21]:
x = np.array([[[12,23,123],
             [38,333,24]],
             [[24,23,123],
             [34,43,24]],
             [[42,23,13],
             [34,43,24]],
             [[42,23,53],
             [34,343,24]]])
print(x.shape)
x.ndim

(4, 2, 3)


3

## Reshape

In [26]:
x = np.array([[0,1],
             [4,3],
             [7,6],
             [66,17]])
x.shape

(4, 2)

In [25]:
x.reshape(8,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [28]:
x.reshape(2,4)

array([[ 0,  1,  4,  3],
       [ 7,  6, 66, 17]])

In [27]:
np.transpose(x)

array([[ 0,  4,  7, 66],
       [ 1,  3,  6, 17]])

In [30]:
x.T

array([[ 0,  4,  7, 66],
       [ 1,  3,  6, 17]])